name: Detect changed packages
description: Detects which packages were changed

inputs:
  token:
    description: The GitHub token
    required: true
  pr:
    description: The number of the PR to check the changed packages of
    required: true
  repo-owner:
    description: The owner of the repository to check
    required: false
  repo-name:
    description: The name of the repository to check
    required: false
  filter-unsupported:
    description: True to filter the unsupported packages from the list (Requires Packit to be installed)
    required: false
    default: false
  output-json:
    description: True to output a json array instead of a space separated list
    required: false
    default: false
outputs:
  packages:
    description: The list of package ids that have been changed, separated by a space

runs:
  using: node24
  main: main.mts
